### ISSUE TITLE
Make the message display a better reactive example

### ISSUE THREAD

**Issue by yschimke** [yschimke/rsocket-demo#7]
ideas - allow setting query, initial request n, submit. Use a reactive data sink for databinding.

cc @josephsavona low priority, but I'm betting my shitty DOM code and search for "peace" will annoy you enough to show me how it's meant to be done :)

**Comment by josephsavona** [comment]
lol. indeed, i'll send a PR later :)

**Comment by yschimke** [comment]
moved to https://github.com/rsocket/rsocket-demo/issues/1
